### ISSUE TITLE
RPC error and np-lib and execute error

### ISSUE THREAD

**Issue by EliasMatta** [egerdnc/NoPixel-3.0-Dump#1]
Hello i got these files and in my server and when I run it an error of attempt to index a nill value (global 'RPC') then i get an issue of same but instead of global rpc its execute

**Comment by EliasMatta** [comment]
ALSO When I start and go in my sever I get fatal error v8 error at MarkCompactCollector semi space copy fallback in old gen.  Allocation failed javascript heap out of memory anyone know fix and what cause

**Comment by egerdnc** [comment]
It is dump stupid asshole.
